### ISSUE TITLE
userStory-1_LandingPage-FirstStyles

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone_userStories#2]
## Value Proposition

**As a** user

**I need** to see that I'm currently on the landing page

**to be able to** have a orientation for further interactions.

## Description

![userStory-1_LandingPage-FirstStyles](https://user-images.githubusercontent.com/115747088/206904947-58eb38a5-15eb-4f5b-aaf3-51c2e76110fc.png)

## Acceptance Criteria

- [ ] The logo of the App is displayed in the Header.
- [ ] Current month is displayed (hardcoded)
- [ ] Search bar as input field is displayed below the current month (just input, no functionality yet)
- [ ] Footer shows Home-Page and Favorite-Page Button (no functionality yet)

## Tasks

(for developers team)

- [ ] create new project with create next-app
- [ ] connect project with github
- [ ] structure project folder by cleaning up the folder first
- [ ] work on branch
- [ ] create Header & Footer component
- [ ] create SearchBar component
- [ ] Add App Logo
- [ ] Add Footer Logos
- [ ] responsive design with grid and basic styling

**Comment by marvinRoellecke** [comment]
Hallo Altan, eine schöne User Story. Das ist Logo ist klasse! 👌

Generell sollen wir ja keine Platzhalter ohne Funktion / Nutzen einbauen. Daher würde ich vorschlagen die Searchbar und den Footer rauszunehmen. 
Vielleicht startest du erstmal mit einer Liste an Gemüse/Obst die im Dezember verfügbar sind.

Das Layout gefällt mir richtig gut :)

**Comment by julialoeschel** [comment]
Hey Altan, 
das was Marvin sagt!
Super Design!

Eine Landigpage Ohne Content für den User ist auch nicht viel Hilfe, der kann in der Regel mit Gemüse mehr anfangen :) Ich würde auch mit der Seite starten, die das Gemüse und Obst anzeigt - jenachdem was die Daten hergeben auch ungeordnet erstmal. 

Auf dem Bild sollten nur Dinge zu sehen sein, die du in der Userstory auch imlementierst. 

Die Landigpage ist eine gute Story (nicht wegschmeißen) für später! 
:octocat:

**Comment by altanguellue** [comment]
Danke für euer Feedback :) Die 2. Userstory beinhaltet genau das, was ihr beide angesprochen habt (Liste der Lebensmittel). Ich würde daher die Reihenfolge dieser Userstories einfach anpassen. Somit wäre Landing-Page die 2. US
