### ISSUE TITLE
userStory-2_FoodList

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone_userStories#3]
## Value Proposition

**As a** user

**I need** to see list of vegetables and fruits

**to be able to** choose which food I want to eat.

## Description

![userStory-2_FoodList](https://user-images.githubusercontent.com/115747088/206905825-87ee3c7e-8379-4403-bb60-65a0cd474a4d.png)

## Acceptance Criteria

- [ ] describe every scenario in detail
- [ ] list of vegetables and fruits are displayed vertically
- [ ] list item informations are displayed referred to a dummy array
- [ ] all list items have img, tag and arrow button
- [ ] overflow is scrollable (vertically)

## Tasks

- [ ] work on branch
- [ ] create dummy array
- [ ] create card component
