### ISSUE TITLE
userStory-3_SearchBar

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone_userStories#4]
## Value Proposition

**As a** user

**I need** to search for vegetables and fruits

**to be able to** find the desired food.

## Description

![userStory-3_SearchBar](https://user-images.githubusercontent.com/115747088/206906315-6fb61db8-46b0-47bf-aeed-e7c69f67c43a.png)

## Acceptance Criteria

- [ ] SearchBar is input field
- [ ] SearchBar checks for string equality with dummy array
- [ ] Card items shown referred to string input in SearchBar

## Tasks

- [ ] work on branch
- [ ] create SearchBar component
- [ ] implement search function
